### PR TITLE
chore: tidy up document

### LINKED ISSUE #132: Spec needs tidy and cleanup
Spec could really use a make tidy up and could use an update of all the cross references. It would make the spec much easier to modify and contribute to. 

@stevefaulkner, you want me to do a quick cleanup?

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #132

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/html-aria/pull/133.html" title="Last updated on May 21, 2019, 1:57 AM UTC (c02fd9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/html-aria/133/5bdf2a6...c02fd9e.html" title="Last updated on May 21, 2019, 1:57 AM UTC (c02fd9e)">Diff</a>

### CODE REVIEW

**Review by stevefaulkner — COMMENTED** [review]
appears to be lots of white space in update??

**Comment by marcoscaceres** [comment]
We can flatten it if you would like? see the tidyconfig.txt

**Comment by marcoscaceres** [comment]
Let me know what you are most comfortable with... I prefer the indenting, as I find table nesting quite challenging to edit manually. We can also boost the line length or whatever you like.

**Comment by stevefaulkner** [comment]
@marcoscaceres I am fine with it being flattened

**Comment by marcoscaceres** [comment]
ok, flat for ya :) what about line length? Keep 80?

**Comment by marcoscaceres** [comment]
@stevefaulkner I managed to fix most of the broken links in the document, except for:

- [ ] examples/nonconforming1.html
- [ ] https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email)
- [ ] https://html.spec.whatwg.org/multipage/interactive-elements.html#attr-valuedef-menu-type-context
- [ ] https://html.spec.whatwg.org/multipage/interactive-elements.html#the-menuitem-element
- [ ] https://html.spec.whatwg.org/multipage/input.html#list-of-options
- [ ] https://html.spec.whatwg.org/multipage/semantics-embedded-content.html#svg
- [ ] https://html.spec.whatwg.org/multipage/input.html#enabling-and-disabling-form-controls-the-disabled-attribute
- [ ] https://html.spec.whatwg.org/multipage/input.html#attr-textarea-readonly
- [ ] https://html.spec.whatwg.org/multipage/input.html#sec-constraint-validation
- [ ] https://html.spec.whatwg.org/multipage/input.html#satisfy-its-constraints

Could you please find equivalent for those in the HTML spec?

**Comment by marcoscaceres** [comment]
Also... about the indenting.... I'm worried that without it, external contributors might have a hard time making changes (specially people like me who are dyslexic). I'd really struggle with flat code, so it might be a service to the community to indent the code.

**Comment by stevefaulkner** [comment]
@marcoscaceres I am also fine with indenting :-)

**Pull request merged**
