### PR TITLE
Fixes #117

### LINKED ISSUE #117: header/footer implicit role needs to include ancestor element's implied role (not just element type)
The [doc conformance table](http://w3c.github.io/html-aria/#docconformance) entry for `<header>` says:
> If not a descendant of an article, aside, main, nav - (changed) or section element role=banner, otherwise No corresponding role

Similarly, the entry for `<footer>` says:
> If not a descendant of an article, aside, main, nav - (changed) or section element role=contentinfo, otherwise No corresponding role

I think the **implied role** for each of the listed elements should also be taken into consideration when determining whether the descendant header or footer has an implicit role, i.e. role=article, complimentary, main, navigation or region.

For example, this could be written (for both `<header>` and `<footer>`) as:
> If not a descendant of an article, aside, main, nav (changed) or section element or an element with role=article, complimentary, main, navigation or region ...

(note that I also deleted the extraneous - hyphen).

### PR DESCRIPTION
**Pull request by carmacleod**
Fixes  #117

***
<a href="https://pr-preview.s3.amazonaws.com/carmacleod/html-aria/pull/118.html" title="Last updated on Sep 29, 2019, 1:54 AM UTC (d10d671)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/html-aria/118/e398a4e...carmacleod:d10d671.html" title="Last updated on Sep 29, 2019, 1:54 AM UTC (d10d671)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Is this stale @stevefaulkner? If still good, @carmacleod, could you fix the merge conflict?

**Review by stevefaulkner — APPROVED** [review]

**Comment by stevefaulkner** [comment]
thanks for PR @carmacleod "This branch has conflicts that must be resolved"

**Comment by carmacleod** [comment]
@marcoscaceres Branch is refreshed; conflicts resolved.

@stevefaulkner Just so you know, I made 2 additional (but tiny) changes:
1. Since `nav` had the `(changed)` keyword, I figure `role=navigation` needed it too - correct?
2. I added the word "then" because with all those words crammed into a table cell, it was confusing to read, and "then" adds clarity.

**Comment by marcoscaceres** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by marcoscaceres** [comment]
Thanks @carmacleod for the update 🧁. Over to @stevefaulkner for final review and to answer your questions.

**Comment by scottaohara** [comment]
@stevefaulkner, @carmacleod 

Looking over this, it is an improvement to clarify the information and I'm going to merge it in, but noting there's additional work to do / consider in #63.

**Pull request merged**
